function pES96oleddt(varargin);
% pES96oleddt( [...] );
% LED Dtct Temp
h = timeplot({'T_Dtct_Src_A'}, ...
      'LED Dtct Temp', ...
      'Dtct Temp', ...
      {'T\_Dtct\_Src\_A'}, ...
      varargin{:} );
