function pES96oddt(varargin);
% pES96oddt( [...] );
% Detector Dtct Temp
h = timeplot({'T_Dtct_A'}, ...
      'Detector Dtct Temp', ...
      'Dtct Temp', ...
      {'T\_Dtct\_A'}, ...
      varargin{:} );
