function pES96ovsvt(varargin);
% pES96ovsvt( [...] );
% Vlv Srb Vlv Temp
h = timeplot({'T_Vlv_UnScb_A','T_Scb_Vlv_A'}, ...
      'Vlv Srb Vlv Temp', ...
      'Vlv Temp', ...
      {'T\_Vlv\_UnScb\_A','T\_Scb\_Vlv\_A'}, ...
      varargin{:} );
