function pES96opdacscpu(varargin);
% pES96opdacscpu( [...] );
% PDACS CPU
h = timeplot({'CPU_Pct','Disk'}, ...
      'PDACS CPU', ...
      'CPU', ...
      {'CPU\_Pct','Disk'}, ...
      varargin{:} );
