function pO3opdacscput(varargin);
% pO3opdacscput( [...] );
% PDACS CPU T
h = timeplot({'vl_cpuT','vl_bdT'}, ...
      'PDACS CPU T', ...
      'CPU T', ...
      {'vl\_cpuT','vl\_bdT'}, ...
      varargin{:} );
