function pO3oledht(varargin);
% pO3oledht( [...] );
% LED Hos Temp
h = timeplot({'T_LED_Hou_A'}, ...
      'LED Hos Temp', ...
      'Hos Temp', ...
      {'T\_LED\_Hou\_A'}, ...
      varargin{:} );
