function pO3oct(varargin);
% pO3oct( [...] );
% Cell Temp
h = timeplot({'T_Cell_In_A','T_A_1','T_A_2','T_A_3','T_A_4','T_Cell_Out_A'}, ...
      'Cell Temp', ...
      'Temp', ...
      {'In','1','2','3','4','Out'}, ...
      varargin{:} );
