function pO3otczone_5(varargin);
% pO3otczone_5( [...] );
% Temp Control Zone 5
h = timeplot({'CT_Inlet','Z5_H_St'}, ...
      'Temp Control Zone 5', ...
      'Zone 5', ...
      {'CT\_Inlet','Z5\_H\_St'}, ...
      varargin{:} );
