function pO3otcz(varargin);
% pO3otcz( [...] );
% Temp Control Zone 1
h = timeplot({'CT_Z1_Mir_A','Z1_H_St'}, ...
      'Temp Control Zone 1', ...
      'Zone 1', ...
      {'CT\_Z1\_Mir\_A','Z1\_H\_St'}, ...
      varargin{:} );
