function pO3ort(varargin);
% pO3ort( [...] );
% Rove Temp
h = timeplot({'T_Rove_1','T_Rove_2','T_Rove_3','T_Rove_4'}, ...
      'Rove Temp', ...
      'Temp', ...
      {'1','2','3','4'}, ...
      varargin{:} );
