function pO3oct(varargin);
% pO3oct( [...] );
% Cell Temp
h = timeplot({'T_A_1','T_A_2','T_A_3','T_A_4'}, ...
      'Cell Temp', ...
      'Temp', ...
      {'1','2','3','4'}, ...
      varargin{:} );
