function pO3odht(varargin);
% pO3odht( [...] );
% Detector Hos Temp
h = timeplot({'T_Dtct_Hou_A'}, ...
      'Detector Hos Temp', ...
      'Hos Temp', ...
      {'T\_Dtct\_Hou\_A'}, ...
      varargin{:} );
