function pO3otczone_2(varargin);
% pO3otczone_2( [...] );
% Temp Control Zone 2
h = timeplot({'CT_Z2_Mir_A','Z2_H_St'}, ...
      'Temp Control Zone 2', ...
      'Zone 2', ...
      {'CT\_Z2\_Mir\_A','Z2\_H\_St'}, ...
      varargin{:} );
